FROM node:22-alpine AS base
COPY package.json package-lock.json .npmrc /usr/application/

FROM base AS base-prod
WORKDIR /usr/application
RUN npm ci --omit "dev"

FROM base-prod AS base-dev
WORKDIR /usr/application
RUN npm ci

FROM base-dev AS build
COPY src/ /usr/application/src
COPY tsconfig.json tsconfig.build.json /usr/application/
WORKDIR /usr/application
ENTRYPOINT [ "sh", "-c", "npm run migration:run" ]
