FROM node:22-slim

RUN apt-get -qy update && apt-get -qy install openssl

RUN mkdir /scripts

COPY ./start.sh /scripts/.
RUN chmod 777 /scripts/start.sh

WORKDIR /usr/application
ENTRYPOINT [ "sh", "-c", "/scripts/start.sh" ]
