INSERT INTO pickit.countries (uuid, code, name) VALUES
(uuid(), 'AFG', 'Afghanistan'),
(uuid(), 'ALB', 'Albania'),
(uuid(), 'ALG', 'Algeria'),
(uuid(), 'ASA', 'American Samoa'),
(uuid(), 'AND', 'Andorra'),
(uuid(), 'ANG', 'Angola'),
(uuid(), 'AIA', 'Anguilla'),
(uuid(), 'ATG', 'Antigua and Barbuda'),
(uuid(), 'ARG', 'Argentina'),
(uuid(), 'ARM', 'Armenia'),
(uuid(), 'ARU', 'Aruba'),
(uuid(), 'AUS', 'Australia'),
(uuid(), 'AUT', 'Austria'),
(uuid(), 'AZE', 'Azerbaijan'),
(uuid(), 'BAH', 'Bahamas'),
(uuid(), 'BHR', 'Bahrain'),
(uuid(), 'BAN', 'Bangladesh'),
(uuid(), 'BRB', 'Barbados'),
(uuid(), 'BLR', 'Belarus'),
(uuid(), 'BEL', 'Belgium'),
(uuid(), 'BLZ', 'Belize'),
(uuid(), 'BEN', 'Benin'),
(uuid(), 'BER', 'Bermuda'),
(uuid(), 'BHU', 'Bhutan'),
(uuid(), 'BOL', 'Bolivia'),
(uuid(), 'BIH', 'Bosnia and Herzegovina'),
(uuid(), 'BOT', 'Botswana'),
(uuid(), 'BRA', 'Brazil'),
(uuid(), 'VGB', 'British Virgin Islands'),
(uuid(), 'BRU', 'Brunei'),
(uuid(), 'BUL', 'Bulgaria'),
(uuid(), 'BFA', 'Burkina Faso'),
(uuid(), 'BDI', 'Burundi'),
(uuid(), 'CAM', 'Cambodia'),
(uuid(), 'CMR', 'Cameroon'),
(uuid(), 'CAN', 'Canada'),
(uuid(), 'CPV', 'Cape Verde'),
(uuid(), 'CAY', 'Cayman Islands'),
(uuid(), 'CTA', 'entral African Republic'),
(uuid(), 'CHA', 'Chad'),
(uuid(), 'CHI', 'Chile'),
(uuid(), 'CHN', 'China'),
(uuid(), 'TPE', 'Chinese Taipei'),
(uuid(), 'COL', 'Colombia'),
(uuid(), 'COM', 'Comoros'),
(uuid(), 'CGO', 'Congo'),
(uuid(), 'COK', 'Cook Islands'),
(uuid(), 'CRC', 'Costa Rica'),
(uuid(), 'CRO', 'Croatia'),
(uuid(), 'CUB', 'Cuba'),
(uuid(), 'CUW', 'Curaçao'),
(uuid(), 'CYP', 'Cyprus'),
(uuid(), 'CZE', 'Czech Republic'),
(uuid(), 'DEN', 'Denmark'),
(uuid(), 'DJI', 'Djibouti'),
(uuid(), 'DMA', 'Dominica'),
(uuid(), 'DOM', 'Dominican Republic'),
(uuid(), 'COD', 'DR Congo'),
(uuid(), 'ECU', 'cuador'),
(uuid(), 'EGY', 'Egypt'),
(uuid(), 'SLV', 'El Salvador'),
(uuid(), 'ENG', 'England'),
(uuid(), 'EQG', 'Equatorial Guinea'),
(uuid(), 'ERI', 'Eritrea'),
(uuid(), 'EST', 'Estonia'),
(uuid(), 'SWZ', 'Eswatini'),
(uuid(), 'ETH', 'Ethiopia'),
(uuid(), 'FRO', 'Faroe Islands'),
(uuid(), 'FIJ', 'Fiji'),
(uuid(), 'FIN', 'Finland'),
(uuid(), 'FRA', 'France'),
(uuid(), 'GAB', 'Gabon'),
(uuid(), 'GAM', 'Gambia'),
(uuid(), 'GEO', 'Georgia'),
(uuid(), 'GER', 'Germany'),
(uuid(), 'GHA', 'Ghana'),
(uuid(), 'GIB', 'Gibraltar'),
(uuid(), 'GRE', 'Greece'),
(uuid(), 'GRN', 'Grenada'),
(uuid(), 'GUM', 'Guam'),
(uuid(), 'GUA', 'Guatemala'),
(uuid(), 'GUI', 'Guinea'),
(uuid(), 'GNB', 'Guinea-Bissau'),
(uuid(), 'GUY', 'Guyana'),
(uuid(), 'HAI', 'Haiti'),
(uuid(), 'HON', 'Honduras'),
(uuid(), 'HKG', 'Hong Kong'),
(uuid(), 'HUN', 'Hungary'),
(uuid(), 'ISL', 'Iceland'),
(uuid(), 'IND', 'India'),
(uuid(), 'IDN', 'Indonesia'),
(uuid(), 'IRN', 'Iran'),
(uuid(), 'IRQ', 'Iraq'),
(uuid(), 'ISR', 'Israel'),
(uuid(), 'ITA', 'Italy'),
(uuid(), 'CIV', 'Ivory Coast'),
(uuid(), 'JAM', 'Jamaica'),
(uuid(), 'JPN', 'Japan'),
(uuid(), 'JOR', 'Jordan'),
(uuid(), 'KAZ', 'Kazakhstan'),
(uuid(), 'KEN', 'Kenya'),
(uuid(), 'KOS', 'Kosovo'),
(uuid(), 'KUW', 'Kuwait'),
(uuid(), 'KGZ', 'Kyrgyzstan'),
(uuid(), 'LAO', 'Laos'),
(uuid(), 'LVA', 'Latvia'),
(uuid(), 'LBN', 'Lebanon'),
(uuid(), 'LES', 'Lesotho'),
(uuid(), 'LBR', 'Liberia'),
(uuid(), 'LBY', 'Libya'),
(uuid(), 'LIE', 'Liechtenstein'),
(uuid(), 'LTU', 'Lithuania'),
(uuid(), 'LUX', 'Luxembourg'),
(uuid(), 'MAC', 'Macau'),
(uuid(), 'MAD', 'Madagascar'),
(uuid(), 'MWI', 'Malawi'),
(uuid(), 'MAS', 'Malaysia'),
(uuid(), 'MDV', 'Maldives'),
(uuid(), 'MLI', 'Mali'),
(uuid(), 'MLT', 'Malta'),
(uuid(), 'MTN', 'Mauritania'),
(uuid(), 'MRI', 'Mauritius'),
(uuid(), 'MEX', 'Mexico'),
(uuid(), 'MDA', 'Moldova'),
(uuid(), 'MNG', 'Mongolia'),
(uuid(), 'MNE', 'Montenegro'),
(uuid(), 'MSR', 'Montserrat'),
(uuid(), 'MAR', 'Morocco'),
(uuid(), 'MOZ', 'Mozambique'),
(uuid(), 'MYA', 'Myanmar'),
(uuid(), 'NAM', 'Namibia'),
(uuid(), 'NEP', 'Nepal'),
(uuid(), 'NED', 'Netherlands'),
(uuid(), 'NCL', 'New Caledonia'),
(uuid(), 'NZL', 'New Zealand'),
(uuid(), 'NCA', 'Nicaragua'),
(uuid(), 'NIG', 'Niger'),
(uuid(), 'NGA', 'Nigeria'),
(uuid(), 'PRK', 'North Korea'),
(uuid(), 'MKD', 'North Macedonia'),
(uuid(), 'NIR', 'Northern Ireland'),
(uuid(), 'NOR', 'Norway'),
(uuid(), 'OMA', 'Oman'),
(uuid(), 'PAK', 'Pakistan'),
(uuid(), 'PLE', 'Palestine'),
(uuid(), 'PAN', 'Panama'),
(uuid(), 'PNG', 'Papua New Guinea'),
(uuid(), 'PAR', 'Paraguay'),
(uuid(), 'PER', 'Peru'),
(uuid(), 'PHI', 'Philippines'),
(uuid(), 'POL', 'Poland'),
(uuid(), 'POR', 'Portugal'),
(uuid(), 'PUR', 'Puerto Rico'),
(uuid(), 'QAT', 'Qatar'),
(uuid(), 'IRL', 'Republic of Ireland'),
(uuid(), 'ROU', 'Romania'),
(uuid(), 'RUS', 'Russia'),
(uuid(), 'RWA', 'Rwanda'),
(uuid(), 'SKN', 'Saint Kitts and Nevis'),
(uuid(), 'LCA', 'Saint Lucia'),
(uuid(), 'VIN', 'Saint Vincent and the Grenadines'),
(uuid(), 'SAM', 'Samoa'),
(uuid(), 'SMR', 'San Marino'),
(uuid(), 'STP', 'São Tomé and Príncipe'),
(uuid(), 'KSA', 'Saudi Arabia'),
(uuid(), 'SCO', 'Scotland'),
(uuid(), 'SEN', 'Senegal'),
(uuid(), 'SRB', 'Serbia'),
(uuid(), 'SEY', 'Seychelles'),
(uuid(), 'SLE', 'Sierra Leone'),
(uuid(), 'SGP', 'Singapore'),
(uuid(), 'SVK', 'Slovakia'),
(uuid(), 'SVN', 'Slovenia'),
(uuid(), 'SOL', 'Solomon Islands'),
(uuid(), 'SOM', 'Somalia'),
(uuid(), 'RSA', 'South Africa'),
(uuid(), 'KOR', 'South Korea'),
(uuid(), 'SSD', 'South Sudan'),
(uuid(), 'ESP', 'Spain'),
(uuid(), 'SRI', 'Sri Lanka'),
(uuid(), 'SDN', 'Sudan'),
(uuid(), 'SUR', 'Suriname'),
(uuid(), 'SWE', 'Sweden'),
(uuid(), 'SUI', 'Switzerland'),
(uuid(), 'SYR', 'Syria'),
(uuid(), 'TAH', 'Tahiti'),
(uuid(), 'TJK', 'Tajikistan'),
(uuid(), 'TAN', 'Tanzania'),
(uuid(), 'THA', 'Thailand'),
(uuid(), 'TLS', 'Timor-Leste'),
(uuid(), 'TOG', 'Togo'),
(uuid(), 'TGA', 'Tonga'),
(uuid(), 'TRI', 'Trinidad and Tobago'),
(uuid(), 'TUN', 'Tunisia'),
(uuid(), 'TUR', 'Turkey'),
(uuid(), 'TKM', 'Turkmenistan'),
(uuid(), 'TCA', 'Turks and Caicos Islands'),
(uuid(), 'UGA', 'Uganda'),
(uuid(), 'UKR', 'Ukraine'),
(uuid(), 'UAE', 'United Arab Emirates'),
(uuid(), 'USA', 'United States'),
(uuid(), 'URU', 'Uruguay'),
(uuid(), 'VIR', 'U.S. Virgin Islands'),
(uuid(), 'UZB', 'Uzbekistan'),
(uuid(), 'VAN', 'Vanuatu'),
(uuid(), 'VEN', 'Venezuela'),
(uuid(), 'VIE', 'Vietnam'),
(uuid(), 'WAL', 'Wales'),
(uuid(), 'YEM', 'Yemen'),
(uuid(), 'ZAM', 'Zambia'),
(uuid(), 'ZIM', 'Zimbabwe');